export const feedbacks = [
  { id: 'feedback-1', image: '/feedbacks/feedback-1.png' },
  { id: 'feedback-2', image: '/feedbacks/feedback-2.png' },
  { id: 'feedback-3', image: '/feedbacks/feedback-3.png' },
  { id: 'feedback-4', image: '/feedbacks/feedback-4.png' },
  { id: 'feedback-5', image: '/feedbacks/feedback-5.png' },
  { id: 'feedback-6', image: '/feedbacks/feedback-6.png' },
  { id: 'feedback-7', image: '/feedbacks/feedback-7.png' },
  { id: 'feedback-8', image: '/feedbacks/feedback-8.png' },
  { id: 'feedback-9', image: '/feedbacks/feedback-9.png' },
  { id: 'feedback-10', image: '/feedbacks/feedback-10.png' },
  { id: 'feedback-11', image: '/feedbacks/feedback-11.png' },
  { id: 'feedback-12', image: '/feedbacks/feedback-12.png' },
  { id: 'feedback-13', image: '/feedbacks/feedback-13.png' },
  { id: 'feedback-14', image: '/feedbacks/feedback-14.png' },
  { id: 'feedback-15', image: '/feedbacks/feedback-15.png' },
  { id: 'feedback-16', image: '/feedbacks/feedback-18.png' },
  { id: 'feedback-17', image: '/feedbacks/feedback-17.png' },
  { id: 'feedback-18', image: '/feedbacks/feedback-16.png' },
  { id: 'feedback-19', image: '/feedbacks/feedback-19.png' },
  { id: 'feedback-20', image: '/feedbacks/feedback-20.png' },
  { id: 'feedback-21', image: '/feedbacks/feedback-21.png' },
];
